# 课程查询接口
POST {{gateway_host}}/content/course/list?pageNo=2&pageSize=10
Content-Type: application/json

{
  "auditStatus": "202002",
  "courseName": ""
}

### 课程计划查询接口
GET {{content_host}}/content/teachplan/117/tree-nodes